# Generated by Django 5.1.7 on 2025-05-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggage',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
