# Generated by Django 5.1.7 on 2025-05-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_luggage_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luggage',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='luggage',
            name='img',
        ),
        migrations.AddField(
            model_name='luggage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
