# Generated by Django 5.1.7 on 2025-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_desc_luggage_description_remove_luggage_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
