# Generated by Django 5.1.7 on 2025-05-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_newfreshstock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewFreshStock',
            new_name='New',
        ),
    ]
