# Generated by Django 5.1.7 on 2025-05-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_newfreshstock_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.AddField(
            model_name='luggage',
            name='category',
            field=models.CharField(choices=[('new', 'New'), ('luggage', 'Luggage')], default='luggage', max_length=20),
        ),
    ]
