# Generated by Django 5.1.7 on 2025-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
